language: python
python: 3.7

services:
  - mysql

before_script:
  - pip install -r requirements.txt
  - pip install flake8

script:
  - flake8
  - source scripts/deploy/dev/environ.sh
  - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS $APP_NAME DEFAULT CHARACTER SET = utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;"

# after_success:
#  - codecov
