apiVersion: v1
kind: Secret
metadata:
  name: {{ include "djangocli.secret.redis.name" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.redis.enabled }}
    host: {{ printf "%s-%s" (include "djangocli.redis.fullname" .) "master" | b64enc | quote }}
    port: {{ printf "%d" (int .Values.redis.master.service.port) | default "6379" | b64enc | quote }}
    password: {{ .Values.redis.auth.password | b64enc | quote }}
  {{- else }}
    host: {{ .Values.externalRedis.host | b64enc | quote }}
    port: {{ printf "%d" (int .Values.externalRedis.port) | b64enc | quote }}
    password: {{ .Values.externalRedis.password | b64enc | quote }}
  {{- end }}
