# Generated by Django 3.1.5 on 2021-03-13 08:55

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=36, verbose_name="名")),
                ("last_name", models.CharField(max_length=64, verbose_name="姓氏")),
                ("birthday", models.DateField(blank=True, null=True, verbose_name="出生日期")),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "作者",
                "verbose_name_plural": "作者",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, verbose_name="书名")),
                ("ISBN", models.CharField(max_length=64, verbose_name="ISBN")),
                ("publication_date", models.DateTimeField(verbose_name="出版日期")),
                ("package_type", models.IntegerField(choices=[(1, "平装"), (2, "精装")], verbose_name="包装类型")),
                ("publisher_id", models.IntegerField(verbose_name="出版社ID")),
                (
                    "author_ids",
                    django_mysql.models.ListCharField(
                        models.IntegerField(verbose_name="作者ID"), max_length=128, size=None, verbose_name="作者ID列表"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "书籍",
                "verbose_name_plural": "书籍",
            },
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, verbose_name="出版社名称")),
                ("address", models.CharField(max_length=128, verbose_name="出版社地址")),
                ("city", models.CharField(max_length=64, verbose_name="所在城市")),
                ("country", models.CharField(max_length=64, verbose_name="所在国家")),
                ("website", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "出版社",
                "verbose_name_plural": "出版社",
            },
        ),
    ]
