# Generated by Django 3.1.5 on 2021-06-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0002_auto_20210313_2043"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"ordering": ["id"], "verbose_name": "作者", "verbose_name_plural": "作者"},
        ),
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["id"], "verbose_name": "书籍", "verbose_name_plural": "书籍"},
        ),
        migrations.AlterModelOptions(
            name="publisher",
            options={"ordering": ["id"], "verbose_name": "出版社", "verbose_name_plural": "出版社"},
        ),
        migrations.AlterField(
            model_name="book",
            name="author_ids",
            field=models.JSONField(default=list, verbose_name="作者ID列表"),
        ),
    ]
