# TODO 当前版本不支持
version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: "djangocli_nginx"
    ports:
      - "2171:80"
    volumes:
      - static_volume:/code/static
      - ./scripts/services/docker/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn wsgi:application --bind 0.0.0.0:2170
    container_name: "djangocli_web"
    expose:
      - 2170
    volumes:
      - static_volume:/code/static

volumes:
  static_volume:
