/* 注意修改成自己的APP_NAME */
CREATE DATABASE `django-cli` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE DATABASE IF NOT EXISTS $APP_NAME DEFAULT CHARACTER SET = utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;
