apiVersion: v1
kind: Secret
metadata:
  name: {{ include "djangocli.secret.mariadb.name" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.mariadb.enabled }}
    {{- if eq .Values.mariadb.architecture "replication" }}
    host: {{ printf "%s-%s" (include "djangocli.mariadb.fullname" .) "primary" | trunc 63 | trimSuffix "-" | b64enc | quote }}
    {{- else }}
    host: {{ printf "%s" (include "djangocli.mariadb.fullname" .) | b64enc | quote }}
    {{- end }}
    port: {{ printf "%d" (int .Values.mariadb.primary.service.port) | default "3306" | b64enc | quote }}
    username: {{ .Values.mariadb.auth.username | b64enc | quote }}
    password: {{ .Values.mariadb.auth.password | b64enc | quote }}
    database: {{ .Values.mariadb.auth.database | b64enc | quote }}
  {{- else }}
    host: {{ .Values.externalMariaDB.host | b64enc | quote }}
    port: {{ printf "%d" (int .Values.externalMariaDB.port) | b64enc | quote }}
    username: {{ .Values.externalMariaDB.username | b64enc | quote }}
    password: {{ .Values.externalMariaDB.password | b64enc | quote }}
    database: {{ .Values.externalMariaDB.database | b64enc | quote }}
  {{- end }}
