apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "djangocli.nginx.fullname" . }}-nginx-conf
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    upstream djangocli {
        server {{ include "djangocli.backend.fullname" . }}:{{ .Values.backend.service.port }};
    }

    server {

        listen {{ .Values.nginx.service.targetPort }};
        server_name _;

        location / {
            proxy_pass http://djangocli;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # 转发流量使用原ip进行访问
            proxy_set_header Host $http_host;
            proxy_redirect off;
        }

        location /static/ {
            alias /code/static/;
        }
    }
