# 当 Release 创建时，构建并推送镜像到DockerHub
# 有关 GitHub release event -> https://docs.github.com/en/rest/reference/repos#get-a-release
# 参考 -> https://github.com/docker/build-push-action
name: Docker build and push

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      # Docker仓库名称
      DOCKER_REPO_NAME: "djangocli"
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: set-up-qemu
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - id: set-up-docker-buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - id: login-to-dockerhub
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: build-and-push
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_REPO_NAME }}:latest,${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_REPO_NAME }}:${{ github.event.release.name }}
          file: scripts/services/k8s/images/app/Dockerfile
