name: Python unittest and codecov
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        django-version: [3.1.5, 3.2.0, 3.2.4]
    env:
      DC_ENV: "dev"
      IS_INJECT_ENV: "False"
      WORKFLOW_DIR: "scripts/workflows"
      MAINLINE_PYTHON_VERSION: "3.7"
      MAINLINE_DJANGO_VERSION: "3.1.5"
      PYTHON_VERSION: ${{ matrix.python-version }}
      DJANGO_VERSION: ${{ matrix.django-version }}

      # 覆盖 support-files/deploy/${{ env.DC_ENV }}/environ.sh，兼容 travis
      DC_MYSQL_PASSWORD: "root"

    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Start MySQL
      run: |
        sudo systemctl start mysql.service
    - name: Init unittest
      run: |
        source support-files/deploy/${{ env.DC_ENV }}/environ.sh
        export DC_MYSQL_PASSWORD=${{ env.DC_MYSQL_PASSWORD }}
        ./scripts/workflows/unittest/install.sh
    - name: Run test and report coverage
      run: |
        source support-files/deploy/${{ env.DC_ENV }}/environ.sh
        export DC_MYSQL_PASSWORD=${{ env.DC_MYSQL_PASSWORD }}
        ./scripts/workflows/unittest/run_test_and_report.sh
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v1
      if: ${{ env.MAINLINE_PYTHON_VERSION == matrix.python-version && env.MAINLINE_DJANGO_VERSION == matrix.django-version }}
